
find_package(Git)
execute_process(COMMAND ${GIT_EXECUTABLE} --git-dir=${CMAKE_SOURCE_DIR}/.git
  describe --abbrev=0 --tags OUTPUT_VARIABLE OUTPUT)
string(REPLACE version- "" OUTPUT ${OUTPUT})
string(REPLACE "." ";" OUTPUT ${OUTPUT})
list(GET OUTPUT 0 VERSION_MAJOR)
list(GET OUTPUT 1 VERSION_MINOR)
list(GET OUTPUT 2 VERSION_REVISION)
string(STRIP ${VERSION_REVISION} VERSION_REVISION)
message("Building version ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_REVISION}")