#pragma once
#include "../controller/controller.h"
#define I2C_ADDR 0x52 
void wii_ext_tick(controller_t *controller);
#ifdef __AVR__
extern uint16_t wii_ext;
#endif
enum ext_type_t {
  WII_NUNCHUK = 0x0000,
  WII_CLASSIC_CONTROLLER = 0x0101,
  WII_CLASSIC_CONTROLLER_PRO = 0x1101,
  WII_THQ_UDRAW_TABLET = 0xF012,
  WII_UBISOFT_DRAWSOME_TABLET = 0xF013,
  WII_GUITAR_HERO_GUITAR_CONTROLLER = 0x0103,
  WII_GUITAR_HERO_DRUM_CONTROLLER = 0x1103,
  WII_DJ_HERO_TURNTABLE = 0x3103,
  WII_TAIKO_NO_TATSUJIN_CONTROLLER = 0x0111,
  WII_MOTION_PLUS_NO_PASSTHROUGH = 0x0405,
  WII_MOTION_PLUS_NUNCHUK_PASSTHROUGH_MODE = 0x0505,
  WII_MOTION_PLUS_CLASSIC_CONTROLLER_PASSTHROUGH_MODE = 0x0705,
  WII_NO_DEVICE = 0xFFFF,
};