#pragma once
#define ORDERED_EP_CONFIG
#define USE_STATIC_OPTIONS \
    (USB_DEVICE_OPT_FULLSPEED | USB_OPT_REG_ENABLED | USB_OPT_MANUAL_PLL)
#define USB_DEVICE_ONLY
#define USE_FLASH_DESCRIPTORS
#define FIXED_CONTROL_ENDPOINT_SIZE 64
#define FIXED_NUM_CONFIGURATIONS 1
#define NO_DEVICE_REMOTE_WAKEUP
#define NO_DEVICE_SELF_POWER
#define USE_INTERNAL_SERIAL 3
#define F_USB F_CPU