#pragma once
#define NUM_DIGITAL_PINS 29
#define PIN_A0 26
#define PIN_A1 27
#define PIN_A2 28
#define NUM_ANALOG_INPUTS 3
#define PIN_WIRE_SDA 26
#define PIN_WIRE_SCL 27
#define PIN_SPI_MOSI 3
#define PIN_SPI_MISO 4
#define PIN_SPI_SCK 6
#define PIN_PS2_ACK 7
#define PIN_PS2_ATT 10
#define PIN_RF_IRQ 7
#define PIN_WAKEUP 8
#define PIN_USB_DP_PIN 20
// RF pins
#define PIN_SPI_SS 5
#define CE 8
#define CSN PIN_SPI_SS