#pragma once
#ifdef __AVR__
#  include "controller/controller.h"
#  define I2C_ADDR 0x52
#  define QUAT_SENS_FP 8388608.f // 2^23
#  define I2C_ADDR_MPU 0x68
#  define MPU_REG_FIFO 0x74
#  define MPU_REG_FIFO_LEN (16 - 1)
void tickWiiExtInput(Controller_t *controller);
void initWiiExtInput(void);
volatile extern uint16_t wiiExtensionID;
#endif
enum WiiExtType {
  WII_NUNCHUK = 0x0000,
  WII_CLASSIC_CONTROLLER = 0x0001,
  WII_CLASSIC_CONTROLLER_PRO = 0x0101,
  WII_THQ_UDRAW_TABLET = 0xFF12,
  WII_UBISOFT_DRAWSOME_TABLET = 0xFF13,
  WII_GUITAR_HERO_GUITAR_CONTROLLER = 0x0003,
  WII_GUITAR_HERO_DRUM_CONTROLLER = 0x0103,
  WII_DJ_HERO_TURNTABLE = 0x0303,
  WII_TAIKO_NO_TATSUJIN_CONTROLLER = 0x0011,
  WII_MOTION_PLUS = 0x0005,
  WII_NO_EXTENSION = 0x180b,
  WII_NOT_INITIALISED = 0xFFFF
};
enum PacketIds {
  INIT_1_ID,
  INIT_1_DATA,
  INIT_2_ID,
  INIT_2_DATA,
  READ_ID,
  DRAWSOME_INIT_1_ID,
  DRAWSOME_INIT_1_DATA,
  DRAWSOME_INIT_2_ID,
  DRAWSOME_INIT_2_DATA,
  HIGH_RES_ID,
  HIGH_RES_DATA,
  READ_DATA
};