#define EEPROM_ADDR_OUTPUT_TYPE
#define EEPROM_ADDR_INPUT_TYPE
#define EEPROM_ADDR_TILT_TYPE
#define EEPROM_ADDR_SUBTYPE
#define EEPROM_ADDR_POLL_RATE
#define EEPROM_ADDR_PIN_BLOCK //size: 15
#define EEPROM_ADDR_DIRECTION_MODE
#define EEPROM_ADDR_WHAMMY_CALIBRATION
#define EEPROM_ADDR_MPU_6050_CALIBRATION
#define EEPROM_ADDR_FRETS_LED_MODE
#define EEPROM_ADDR_KEY_BINDING_BLOCK //size: 12
