#pragma once
#define NONE 0
#define INVALID_PIN 0xFF

// Tilt detection
enum tilt { MPU_6050 = 1, GRAVITY, ANALOGUE };

// Input types
enum input { WII = 1, DIRECT };

enum subtype {
  XINPUT_GAMEPAD_SUBTYPE=1,
  XINPUT_WHEEL_SUBTYPE,
  XINPUT_ARCADE_STICK_SUBTYPE,
  XINPUT_FLIGHT_STICK_SUBTYPE,
  XINPUT_DANCE_PAD_SUBTYPE,
  XINPUT_GUITAR_SUBTYPE,
  XINPUT_GUITAR_ALTERNATE_SUBTYPE,
  XINPUT_DRUM_SUBTYPE,
  XINPUT_GUITAR_BASS_SUBTYPE=11,
  XINPUT_ARCADE_PAD_SUBTYPE=19,
  KEYBOARD_SUBTYPE,
  SWITCH_GAMEPAD_SUBTYPE,
  PS3_GAMEPAD_SUBTYPE,
  PS3_GUITAR_GH_SUBTYPE,
  PS3_GUITAR_RB_SUBTYPE,
  PS3_DRUM_GH_SUBTYPE,
  PS3_DRUM_RB_SUBTYPE
};



// Orientations for gyros
enum gyro {
    POSITIVE_Z,
    NEGATIVE_Z,
    POSITIVE_Y,
    NEGATIVE_Y,
    POSITIVE_X,
    NEGATIVE_X
};

// Firmware types
enum firmware_type {
    GUITAR_DEVICE_TYPE=0xfea123,
    ARDWIINO_DEVICE_TYPE=0xa2d414
};

// Fret Modes
enum fret_mode {
    FRET_MODE_NEGATIVE,
    FRET_MODE_POSITIVE,
    FRET_MODE_WS2812,
    FRET_MODE_APA102
};

