#include <gtest/gtest.h>
#include <fstream>
#include <regex>
#include <sstream>
#include <string>
#include <vector>
#include "firmware_descriptors.hpp"
#include "hid_descriptor.hpp"
#include "source_check.hpp"

// Over BLE (HID over GATT) a report can only be sent or received if the GATT database has a Report
// characteristic whose Report Reference (id, type) names it: btstack's hids_device looks the report up
// by id and type (hids_device_send_input_report_for_id), and sizes it from the report map
// (btstack_hid_get_report_size_for_id). hids_device serves the first HID service in the database.
//
// BTGamepadDevice::initialize (bt_gamepad.cpp) picks one database per mode, each with its own report map:
//  - gamepad (and dance pad / instrument) profiles: src/emulation/bt/bt.gatt -> bt_profile.h, with
//    desc_hid_report_hat / desc_hid_report_buttons
//  - keyboard / mouse profiles: bt_keyboard.gatt -> bt_keyboard_profile.h, with desc_hid_report_keyboard
//  - config only (no profile uses bluetooth): bt_config.gatt -> bt_config_profile.h, no gamepad service
// Each also has the config HID service (bt_config_service.cpp) and the Web Bluetooth config service.
// The firmware compiles the checked in headers generated by lib/btstack/tool/compile_gatt.py, so the tests
// read those and check they are in step with the .gatt files.

using namespace hid_desc;

namespace
{
struct ReportRef
{
    uint8_t id;
    uint8_t type; // 1 input, 2 output, 3 feature (HOGP Report Reference)
    bool operator==(const ReportRef &o) const { return id == o.id && type == o.type; }
};

struct Service
{
    std::string name;
    std::vector<ReportRef> reports;
    bool hid() const { return name == "ORG_BLUETOOTH_SERVICE_HUMAN_INTERFACE_DEVICE"; }
};

std::vector<std::string> read_lines(const std::string &relative)
{
    std::ifstream file(std::string(SANTROLLER_ROOT) + "/" + relative);
    std::vector<std::string> lines;
    std::string line;
    while (std::getline(file, line))
        lines.push_back(line);
    return lines;
}

// The services of a .gatt file in order, with btstack's hids.gatt expanded in place. compile_gatt.py
// writes Report Reference values as hex bytes.
std::vector<Service> gatt_services(const std::string &gatt)
{
    std::vector<Service> services;
    std::vector<std::string> lines = read_lines(gatt);
    EXPECT_FALSE(lines.empty()) << "can't read " << gatt;
    std::vector<std::string> expanded;
    for (const auto &line : lines)
    {
        if (line.rfind("#import <hids.gatt>", 0) == 0)
        {
            auto hids = read_lines("lib/btstack/src/ble/gatt-service/hids.gatt");
            EXPECT_FALSE(hids.empty()) << "can't read hids.gatt";
            expanded.insert(expanded.end(), hids.begin(), hids.end());
        }
        else if (line.rfind("#import", 0) == 0)
        {
            // another standard service (battery, device information), with no reports
            expanded.push_back("PRIMARY_SERVICE, IMPORTED");
        }
        else
        {
            expanded.push_back(line);
        }
    }
    const std::regex service(R"(^PRIMARY_SERVICE\s*,\s*(\S+))");
    const std::regex reference(R"(^REPORT_REFERENCE\s*,\s*READ\s*,\s*([0-9A-Fa-f]+)\s*,\s*([0-9A-Fa-f]+))");
    for (const auto &line : expanded)
    {
        std::smatch m;
        if (std::regex_search(line, m, service))
        {
            services.push_back({m[1].str(), {}});
        }
        else if (std::regex_search(line, m, reference))
        {
            EXPECT_FALSE(services.empty());
            services.back().reports.push_back({uint8_t(std::stoul(m[1], nullptr, 16)), uint8_t(std::stoul(m[2], nullptr, 16))});
        }
    }
    return services;
}

// The same from a generated header, whose comments list each attribute as compile_gatt.py saw it
// ("// 0x0021 REPORT_REFERENCE-READ-1-1")
std::vector<Service> header_services(const std::string &header)
{
    std::vector<Service> services;
    auto lines = read_lines(header);
    EXPECT_FALSE(lines.empty()) << "can't read " << header;
    const std::regex service(R"(^\s*// 0x[0-9a-fA-F]+ PRIMARY_SERVICE-(\S+))");
    const std::regex reference(R"(^\s*// 0x[0-9a-fA-F]+ REPORT_REFERENCE-READ-([0-9A-Fa-f]+)-([0-9A-Fa-f]+))");
    for (const auto &line : lines)
    {
        std::smatch m;
        if (std::regex_search(line, m, service))
        {
            services.push_back({m[1].str(), {}});
        }
        else if (std::regex_search(line, m, reference))
        {
            EXPECT_FALSE(services.empty());
            services.back().reports.push_back({uint8_t(std::stoul(m[1], nullptr, 16)), uint8_t(std::stoul(m[2], nullptr, 16))});
        }
    }
    return services;
}

// The 16 byte GATT database hash compile_gatt.py put in the header (the value line after its comment)
std::string database_hash(const std::string &header)
{
    auto lines = read_lines(header);
    for (size_t i = 0; i + 2 < lines.size(); i++)
        if (lines[i].find("VALUE CHARACTERISTIC-GATT_DATABASE_HASH") != std::string::npos)
            return lines[i + 2];
    return "";
}

std::vector<Service> only_hid(const std::vector<Service> &services)
{
    std::vector<Service> out;
    for (const auto &s : services)
        if (s.hid())
            out.push_back(s);
    return out;
}

bool has_ref(const Service &s, uint8_t id, uint8_t type)
{
    for (const auto &r : s.reports)
        if (r.id == id && r.type == type)
            return true;
    return false;
}

bool has_service(const std::vector<Service> &services, const std::string &name)
{
    for (const auto &s : services)
        if (s.name == name)
            return true;
    return false;
}

ReportType report_type(uint8_t type)
{
    return type == 1 ? ReportType::Input : type == 2 ? ReportType::Output : ReportType::Feature;
}

const char *const kWebConfigService = "53414E54-524F-4C4C-4552-000000000000";

// A GATT database and the mode that uses it
struct Database
{
    std::string name;
    std::string gatt;
    std::string header;
    // the report maps hids_device serves from the first HID service (none for config only)
    std::vector<std::vector<uint8_t>> report_maps;
    // input reports the mode sends by id, and output reports it reads
    std::vector<uint8_t> inputs;
    std::vector<uint8_t> outputs;
};

std::vector<Database> databases()
{
    return {
        // BTGamepadDevice::process / send_report: the gamepad report through the first input characteristic,
        // the capabilities by id; rumble / commands and the capabilities request come in as output reports
        {"Gamepad", "src/emulation/bt/bt.gatt", "include/emulation/bt/bt_profile.h",
         {bytes_of(desc_hid_report_hat), bytes_of(desc_hid_report_buttons)},
         {uint8_t(ReportIdGamepad), uint8_t(ReportIdSantrollerCapabilities)},
         {uint8_t(ReportIdGamepad), uint8_t(ReportIdSantrollerCapabilities)}},
        // BTGamepadDevice::process for KeyboardMouse: keyboard, media keys and mouse by id; lock lights come in
        {"Keyboard", "src/emulation/bt/bt_keyboard.gatt", "include/emulation/bt/bt_keyboard_profile.h",
         {std::vector<uint8_t>(desc_hid_report_keyboard, desc_hid_report_keyboard + desc_hid_report_keyboard_len)},
         {KEYBOARD_REPORT_ID, MOUSE_REPORT_ID, CONSUMER_REPORT_ID},
         {KEYBOARD_REPORT_ID}},
        {"ConfigOnly", "src/emulation/bt/bt_config.gatt", "include/emulation/bt/bt_config_profile.h", {}, {}, {}},
    };
}

class BtGattDatabase : public ::testing::TestWithParam<Database>
{
};

std::string database_name(const ::testing::TestParamInfo<Database> &info) { return info.param.name; }
} // namespace

// The headers have to be regenerated whenever a .gatt file changes, e.g.
//   lib/btstack/tool/compile_gatt.py src/emulation/bt/bt.gatt include/emulation/bt/bt_profile.h
TEST_P(BtGattDatabase, GeneratedHeaderMatchesTheGattFile)
{
    auto from_gatt = gatt_services(GetParam().gatt);
    auto from_header = header_services(GetParam().header);
    ASSERT_EQ(from_gatt.size(), from_header.size());
    for (size_t i = 0; i < from_gatt.size(); i++)
    {
        if (from_gatt[i].name != "IMPORTED")
        {
            EXPECT_EQ(from_gatt[i].name, from_header[i].name) << "service " << i;
        }
        ASSERT_EQ(from_gatt[i].reports.size(), from_header[i].reports.size()) << "service " << i;
        for (size_t j = 0; j < from_gatt[i].reports.size(); j++)
            EXPECT_TRUE(from_gatt[i].reports[j] == from_header[i].reports[j]) << "service " << i << " report " << j;
    }
}

// The configurator finds the device by the config HID service (bt_config_service.cpp) or, from Web
// Bluetooth, by the Santroller config service UUID (BluetoothConfigDevice.ts): both in every mode
TEST_P(BtGattDatabase, HasTheConfigServices)
{
    auto services = header_services(GetParam().header);
    auto hid = only_hid(services);
    ASSERT_EQ(hid.size(), GetParam().report_maps.empty() ? 1u : 2u);
    EXPECT_TRUE(has_service(services, kWebConfigService));
    EXPECT_TRUE(has_service(services, "GATT_SERVICE")) << "database hash";

    const Service &config = hid.back();
    auto d = parse(kConfig);
    ASSERT_TRUE(d.ok) << d.error;
    // bt_config_service.cpp sizes each report from hid_config_report_descriptor(), capped at 64
    for (const auto &r : config.reports)
    {
        SCOPED_TRACE(::testing::Message() << "report 0x" << std::hex << int(r.id) << " type " << int(r.type));
        EXPECT_GT(d.report_bytes(report_type(r.type), r.id), 0u);
        EXPECT_LE(d.report_bytes(report_type(r.type), r.id), 64u);
    }
    EXPECT_TRUE(has_ref(config, ReportIdConfig, 1)) << "config events";
    EXPECT_TRUE(has_ref(config, ReportIdUploadFirmware, 2)) << "firmware upload";
}

// Every report the mode's HID service references is in the mode's report map (or btstack sizes it as 0
// and hosts see a characteristic for a report the map doesn't have)
TEST_P(BtGattDatabase, CharacteristicsAreInTheReportMap)
{
    if (GetParam().report_maps.empty())
        GTEST_SKIP() << "no gamepad / keyboard HID service";
    auto hid = only_hid(header_services(GetParam().header));
    ASSERT_EQ(hid.size(), 2u);
    for (const auto &map : GetParam().report_maps)
    {
        auto d = parse(map);
        ASSERT_TRUE(d.ok) << d.error;
        for (const auto &r : hid[0].reports)
            EXPECT_GT(d.report_bytes(report_type(r.type), r.id), 0u) << "report " << int(r.id) << " type " << int(r.type);
    }
}

// Every report the mode sends or reads has a characteristic, and they all fit bt_gamepad.cpp's
// report_storage (6 entries; hids_device stops at the storage size)
TEST_P(BtGattDatabase, ReportsTheModeUsesHaveCharacteristics)
{
    if (GetParam().report_maps.empty())
        GTEST_SKIP() << "no gamepad / keyboard HID service";
    auto hid = only_hid(header_services(GetParam().header));
    ASSERT_EQ(hid.size(), 2u);
    for (uint8_t id : GetParam().inputs)
        EXPECT_TRUE(has_ref(hid[0], id, 1)) << "input report " << int(id);
    for (uint8_t id : GetParam().outputs)
        EXPECT_TRUE(has_ref(hid[0], id, 2)) << "output report " << int(id);
    EXPECT_LE(hid[0].reports.size(), 6u);
    // hids_device_send_input_report (no id) uses the first input characteristic: the main report
    for (const auto &r : hid[0].reports)
    {
        if (r.type != 1)
            continue;
        EXPECT_EQ(r.id, GetParam().inputs.front());
        break;
    }
}

INSTANTIATE_TEST_SUITE_P(Modes, BtGattDatabase, ::testing::ValuesIn(databases()), database_name);

// Hosts cache the database per bonded device and re-discover when its hash changes, so each mode's
// database has to hash differently
TEST(BtGatt, DatabaseHashesDiffer)
{
    std::vector<std::string> hashes;
    for (const auto &db : databases())
    {
        hashes.push_back(database_hash(db.header));
        EXPECT_FALSE(hashes.back().empty()) << db.name;
    }
    for (size_t i = 0; i < hashes.size(); i++)
        for (size_t j = i + 1; j < hashes.size(); j++)
            EXPECT_NE(hashes[i], hashes[j]) << databases()[i].name << " vs " << databases()[j].name;
}

// BTGamepadDevice::initialize picks the keyboard database for keyboard / mouse profiles, the config only
// one when no profile uses bluetooth, and the gamepad one otherwise
TEST(BtGatt, DeviceSelectsTheDatabasePerMode)
{
    const std::string source = firmware_source("src/emulation/bt/bt_gamepad.cpp");
    EXPECT_NE(source.find("constuint8_t*db=profile_data;"), std::string::npos);
    EXPECT_NE(source.find("db=bt_config_only_profile(&config_start,&config_end);"), std::string::npos);
    EXPECT_NE(source.find("elseif(subtype==SubType_KeyboardMouse){db=bt_keyboard_profile(&config_start,&config_end);}"),
              std::string::npos);
    EXPECT_NE(source.find("caseSubType_KeyboardMouse:hids_device_init_with_storage(0,desc_hid_report_keyboard,"), std::string::npos);
    EXPECT_NE(firmware_source("src/emulation/bt/bt_descriptors.cpp").find("#include\"emulation/bt/bt_keyboard_profile.h\""),
              std::string::npos);
}

// The Web Bluetooth config service has one characteristic per feature report id (s_web_report_ids in
// bt_config_service.cpp), sized from the config descriptor's feature reports
TEST(BtGatt, WebConfigReportIdsAreConfigFeatures)
{
    const std::string source = firmware_source("src/emulation/bt/bt_config_service.cpp");
    std::smatch m;
    ASSERT_TRUE(std::regex_search(source, m, std::regex(R"(s_web_report_ids\[\]=\{([^}]*)\})")));
    auto d = parse(kConfig);
    ASSERT_TRUE(d.ok) << d.error;
    std::stringstream ids(m[1].str());
    std::string id;
    int count = 0;
    while (std::getline(ids, id, ','))
    {
        const uint8_t report = uint8_t(std::stoul(id, nullptr, 0));
        EXPECT_GT(d.report_bytes(ReportType::Feature, report), 0u) << "report 0x" << std::hex << int(report);
        count++;
    }
    EXPECT_GT(count, 0);
}
