#define GH_MIDI_NOTE_KICK 36
#define GH_MIDI_NOTE_RED 38
#define GH_MIDI_NOTE_GREEN 45
#define GH_MIDI_NOTE_YELLOW 46
#define GH_MIDI_NOTE_BLUE 48
#define GH_MIDI_NOTE_ORANGE 49
#define GH_MIDI_NOTE_KICK2 100

#define RB_MIDI_NOTE_KICK 36
#define RB_MIDI_NOTE_RED 38
#define RB_MIDI_NOTE_GREEN 41
#define RB_MIDI_NOTE_YELLOW 48
#define RB_MIDI_NOTE_BLUE 45
#define RB_MIDI_NOTE_GREEN_CYMBAL 49
#define RB_MIDI_NOTE_YELLOW_CYMBAL 22
#define RB_MIDI_NOTE_BLUE_CYMBAL 51
#define RB_MIDI_NOTE_KICK2 44