#include <stdint.h>
enum SerialCommands {
    COMMAND_REBOOT=0x30,
    COMMAND_JUMP_BOOTLOADER,
    COMMAND_JUMP_BOOTLOADER_UNO,
    COMMAND_READ_CONFIG,
    COMMAND_READ_F_CPU,
    COMMAND_READ_BOARD,
    COMMAND_READ_DIGITAL,
    COMMAND_READ_ANALOG,
    COMMAND_READ_PS2,
    COMMAND_READ_WII,
    COMMAND_READ_DJ,
    COMMAND_READ_GH5,
    COMMAND_READ_GHWT,
    COMMAND_GET_EXTENSION,
    COMMAND_SET_LEDS,
    MAX
};
