#include <stdint.h>
enum SerialCommands {
    COMMAND_REBOOT=0x30,
    COMMAND_JUMP_BOOTLOADER,
    COMMAND_JUMP_BOOTLOADER_UNO,
    COMMAND_READ_CONFIG,
    COMMAND_READ_F_CPU,
    COMMAND_READ_BOARD,
    COMMAND_FIND_DIGITAL,
    COMMAND_FIND_ANALOG,
    COMMAND_GET_FOUND,
    COMMAND_GET_EXTENSION,
    COMMAND_SET_LEDS,
    COMMAND_SET_SP,
    MAX
};
