#pragma once
#define ORDERED_EP_CONFIG
#define USB_DEVICE_ONLY
#define USE_RAM_DESCRIPTORS
#define FIXED_CONTROL_ENDPOINT_SIZE 64
#define DEVICE_STATE_AS_GPIOR 2  // GPIOR0 is used for the RX ISR with cbi()
#define FIXED_NUM_CONFIGURATIONS 1
#define NO_DEVICE_REMOTE_WAKEUP
#define NO_DEVICE_SELF_POWER
#define USE_INTERNAL_SERIAL 3
#define F_USB F_CPU
#ifdef __AVR_ATmega32U4__
#define INTERRUPT_CONTROL_ENDPOINT 1
#endif

#ifdef DETECT
#define USE_STATIC_OPTIONS \
    (USB_DEVICE_OPT_FULLSPEED | USB_OPT_REG_ENABLED | USB_OPT_MANUAL_PLL)
#else
#define USE_STATIC_OPTIONS \
    (USB_DEVICE_OPT_FULLSPEED | USB_OPT_REG_ENABLED | USB_OPT_AUTO_PLL)
#endif