#!/usr/bin/env python3
"""
Packages Xbox One wireless dongle firmwares into a static flash binary and header.
"""

import argparse
import gzip
import os
import struct
import sys

HEADER_FORMAT = "< 9I 7I"
MAGIC = 0x31425821  # "!XB1"
VERSION = 1
HEADER_SIZE = 64  # 16 * 4 bytes

def main():
    parser = argparse.ArgumentParser(description="Package Xbox One dongle firmwares into static flash image.")
    parser.add_argument("--firmware-dir", required=True, help="Directory containing raw dongle firmwares")
    parser.add_argument("--output-dir", required=True, help="Directory to output binary and header files")
    parser.add_argument("--partition-size-kb", type=int, default=96, help="Partition size in KB (default: 96)")
    parser.add_argument("--flash-offset", type=lambda x: int(x, 0), default=0xA000, help="Flash offset (default: 0xA000)")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    partition_size_bytes = args.partition_size_kb * 1024

    fw_02e6_path = os.path.join(args.firmware_dir, "xone_dongle_02e6.bin")
    fw_02fe_path = os.path.join(args.firmware_dir, "xone_dongle_02fe.bin")

    have_02e6 = os.path.isfile(fw_02e6_path)
    have_02fe = os.path.isfile(fw_02fe_path)

    if not have_02e6 or not have_02fe:
        print(f"Warning: Dongle firmware files missing in {args.firmware_dir} (have 02e6: {have_02e6}, 02fe: {have_02fe})", file=sys.stderr)
        data_02e6 = b""
        data_02fe = b""
        comp_02e6 = b""
        comp_02fe = b""
    else:
        with open(fw_02e6_path, "rb") as f:
            data_02e6 = f.read()
        with open(fw_02fe_path, "rb") as f:
            data_02fe = f.read()

        comp_02e6 = gzip.compress(data_02e6, compresslevel=9, mtime=0)
        comp_02fe = gzip.compress(data_02fe, compresslevel=9, mtime=0)

    # Calculate offsets
    offset_02e6 = HEADER_SIZE
    # 4-byte align the next blob
    offset_02fe = offset_02e6 + len(comp_02e6)
    if offset_02fe % 4 != 0:
        offset_02fe += 4 - (offset_02fe % 4)

    total_data_len = offset_02fe + len(comp_02fe)
    if total_data_len > partition_size_bytes:
        print(f"Error: Compressed firmwares ({total_data_len} bytes) exceed partition size ({partition_size_bytes} bytes)", file=sys.stderr)
        sys.exit(1)

    # Build header
    if have_02e6 and have_02fe:
        header_magic = MAGIC
        header_version = VERSION
    else:
        header_magic = 0
        header_version = 0

    reserved = [0] * 7
    header_bytes = struct.pack(
        HEADER_FORMAT,
        header_magic,
        header_version,
        partition_size_bytes,
        offset_02e6,
        len(comp_02e6),
        len(data_02e6),
        offset_02fe,
        len(comp_02fe),
        len(data_02fe),
        *reserved
    )
    assert len(header_bytes) == HEADER_SIZE

    # Assemble binary
    binary = bytearray(header_bytes)
    binary.extend(comp_02e6)
    if len(binary) < offset_02fe:
        binary.extend(b"\x00" * (offset_02fe - len(binary)))
    binary.extend(comp_02fe)

    # Pad rest of partition with 0xFF (flash erased state)
    if len(binary) < partition_size_bytes:
        binary.extend(b"\xFF" * (partition_size_bytes - len(binary)))

    bin_output_path = os.path.join(args.output_dir, "xbox_dongle_firmware.bin")
    with open(bin_output_path, "wb") as f:
        f.write(binary)
    print(f"Wrote {bin_output_path} ({len(binary)} bytes, data: {total_data_len} bytes)")

    # Write C header
    header_output_path = os.path.join(args.output_dir, "xbox_dongle_firmware.h")
    flash_address = 0x10000000 + args.flash_offset
    header_content = f"""/* Auto-generated by package_dongle_firmware.py - DO NOT EDIT */
#ifndef XBOX_DONGLE_FIRMWARE_H
#define XBOX_DONGLE_FIRMWARE_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#define XBOX_STATIC_FIRMWARE_MAGIC 0x{MAGIC:08X}
#define XBOX_STATIC_FIRMWARE_VERSION {VERSION}
#define XBOX_STATIC_FIRMWARE_OFFSET 0x{args.flash_offset:X}
#define XBOX_STATIC_FIRMWARE_ADDRESS 0x{flash_address:08X}
#define XBOX_STATIC_FIRMWARE_PARTITION_SIZE ({args.partition_size_kb} * 1024)

struct __attribute__((packed)) XboxStaticFirmwareHeader
{{
    uint32_t magic;
    uint32_t version;
    uint32_t total_size;
    uint32_t fw_02e6_offset;
    uint32_t fw_02e6_compressed_len;
    uint32_t fw_02e6_len;
    uint32_t fw_02fe_offset;
    uint32_t fw_02fe_compressed_len;
    uint32_t fw_02fe_len;
    uint32_t reserved[7];
}};

static inline const struct XboxStaticFirmwareHeader *xbox_get_static_firmware_header(void)
{{
    const struct XboxStaticFirmwareHeader *header =
        (const struct XboxStaticFirmwareHeader *)(XBOX_STATIC_FIRMWARE_ADDRESS);
    if (header->magic != XBOX_STATIC_FIRMWARE_MAGIC || header->version != XBOX_STATIC_FIRMWARE_VERSION)
    {{
        return NULL;
    }}
    return header;
}}

#endif // XBOX_DONGLE_FIRMWARE_H
"""
    with open(header_output_path, "w") as f:
        f.write(header_content)
    print(f"Wrote {header_output_path}")

if __name__ == "__main__":
    main()

