# Convert firmware binaries to C arrays with gzip compression
# This script runs during CMake configuration to generate firmware_data.c

set(FIRMWARE_DIR "${CMAKE_BINARY_DIR}/firmware")
set(GENERATED_DIR "${CMAKE_BINARY_DIR}/generated")
set(OUTPUT_FILE "${GENERATED_DIR}/firmware_data.c")
set(HEADER_FILE "${GENERATED_DIR}/firmware_data.h")

# Create generated directory if it doesn't exist
file(MAKE_DIRECTORY "${GENERATED_DIR}")

# List of firmware PIDs to convert (only external USB dongles)
set(FIRMWARE_PIDS "02e6" "02fe")

# Find gzip
find_program(GZIP_EXECUTABLE gzip)
if(NOT GZIP_EXECUTABLE)
    message(WARNING "gzip not found - firmware will not be compressed")
    set(USE_COMPRESSION FALSE)
else()
    message(STATUS "Using gzip compression for firmware data")
    set(USE_COMPRESSION TRUE)
endif()

message(STATUS "Converting firmware binaries to C arrays...")

# Start output files
file(WRITE "${OUTPUT_FILE}" "// Auto-generated by CMake - DO NOT EDIT\n")
file(APPEND "${OUTPUT_FILE}" "#include \"firmware_data.h\"\n\n")
file(APPEND "${OUTPUT_FILE}" "// Xbox Wireless Adapter Firmwares\n")
file(APPEND "${OUTPUT_FILE}" "// Generated from firmware/*.bin files\n\n")

# Start header file
file(WRITE "${HEADER_FILE}" "// Auto-generated by CMake - DO NOT EDIT\n")
file(APPEND "${HEADER_FILE}" "#ifndef FIRMWARE_DATA_H\n")
file(APPEND "${HEADER_FILE}" "#define FIRMWARE_DATA_H\n\n")
file(APPEND "${HEADER_FILE}" "#include <stdint.h>\n\n")
file(APPEND "${HEADER_FILE}" "// Xbox Wireless Adapter Firmwares\n")
file(APPEND "${HEADER_FILE}" "// Generated from firmware/*.bin files\n\n")

set(FIRMWARE_CONVERTED 0)

# Function to convert a single firmware
foreach(PID ${FIRMWARE_PIDS})
    set(FIRMWARE_FILE "${FIRMWARE_DIR}/xone_dongle_${PID}.bin")
    
    if(EXISTS "${FIRMWARE_FILE}")
        file(SIZE "${FIRMWARE_FILE}" FIRMWARE_SIZE)
        
        # Compress firmware if gzip is available
        if(USE_COMPRESSION)
            set(COMPRESSED_FILE "${GENERATED_DIR}/xone_dongle_${PID}.bin.gz")
            execute_process(
                COMMAND ${GZIP_EXECUTABLE} -9 -c "${FIRMWARE_FILE}"
                OUTPUT_FILE "${COMPRESSED_FILE}"
                RESULT_VARIABLE GZIP_RESULT
            )
            
            if(GZIP_RESULT EQUAL 0 AND EXISTS "${COMPRESSED_FILE}")
                file(SIZE "${COMPRESSED_FILE}" COMPRESSED_SIZE)
                math(EXPR SAVINGS "${FIRMWARE_SIZE} - ${COMPRESSED_SIZE}")
                math(EXPR RATIO "(${COMPRESSED_SIZE} * 100) / ${FIRMWARE_SIZE}")
                message(STATUS "  [${PID}] Compressed ${FIRMWARE_SIZE} -> ${COMPRESSED_SIZE} bytes (${RATIO}%, saved ${SAVINGS} bytes)")
                
                set(FIRMWARE_FILE "${COMPRESSED_FILE}")
                set(ACTUAL_SIZE ${COMPRESSED_SIZE})
                set(IS_COMPRESSED TRUE)
            else()
                message(WARNING "  [${PID}] Compression failed, using uncompressed")
                set(ACTUAL_SIZE ${FIRMWARE_SIZE})
                set(IS_COMPRESSED FALSE)
            endif()
        else()
            message(STATUS "  [${PID}] Converting xone_dongle_${PID}.bin (${FIRMWARE_SIZE} bytes, uncompressed)")
            set(ACTUAL_SIZE ${FIRMWARE_SIZE})
            set(IS_COMPRESSED FALSE)
        endif()
        
        # Read binary file (compressed or uncompressed)
        file(READ "${FIRMWARE_FILE}" FIRMWARE_HEX HEX)
        
        # Convert hex string to C array format
        string(LENGTH "${FIRMWARE_HEX}" HEX_LENGTH)
        
        # Write array declaration with compression info
        if(IS_COMPRESSED)
            file(APPEND "${OUTPUT_FILE}" "// xone_dongle_${PID}.bin (compressed: ${ACTUAL_SIZE} bytes, original: ${FIRMWARE_SIZE} bytes)\n")
        else()
            file(APPEND "${OUTPUT_FILE}" "// xone_dongle_${PID}.bin (${ACTUAL_SIZE} bytes, uncompressed)\n")
        endif()
        file(APPEND "${OUTPUT_FILE}" "const uint8_t mt76_firmware_${PID}[] = {\n")
        
        # Process hex string in chunks
        set(BYTE_COUNT 0)
        set(LINE_BUFFER "    ")
        
        math(EXPR NUM_BYTES "${HEX_LENGTH} / 2")
        
        foreach(BYTE_INDEX RANGE 0 ${NUM_BYTES})
            if(BYTE_INDEX EQUAL NUM_BYTES)
                break()
            endif()
            
            # Extract two hex characters
            math(EXPR HEX_POS "${BYTE_INDEX} * 2")
            string(SUBSTRING "${FIRMWARE_HEX}" ${HEX_POS} 2 BYTE_HEX)
            
            # Add to line buffer
            string(APPEND LINE_BUFFER "0x${BYTE_HEX}")
            
            math(EXPR BYTE_COUNT "${BYTE_COUNT} + 1")
            
            # Add comma if not last byte
            math(EXPR LAST_BYTE "${NUM_BYTES} - 1")
            if(NOT BYTE_INDEX EQUAL LAST_BYTE)
                string(APPEND LINE_BUFFER ", ")
            endif()
            
            # Write line every 12 bytes
            math(EXPR LINE_POS "${BYTE_COUNT} % 12")
            if(LINE_POS EQUAL 0)
                string(APPEND LINE_BUFFER "\n")
                file(APPEND "${OUTPUT_FILE}" "${LINE_BUFFER}")
                set(LINE_BUFFER "    ")
            endif()
        endforeach()
        
        # Write remaining bytes
        if(NOT LINE_BUFFER STREQUAL "    ")
            string(APPEND LINE_BUFFER "\n")
            file(APPEND "${OUTPUT_FILE}" "${LINE_BUFFER}")
        endif()
        
        file(APPEND "${OUTPUT_FILE}" "};\n\n")
        
        # Add to header - define size macros and compression flag
        if(IS_COMPRESSED)
            file(APPEND "${HEADER_FILE}" "#define mt76_firmware_${PID}_compressed_len ${ACTUAL_SIZE}\n")
            file(APPEND "${HEADER_FILE}" "#define mt76_firmware_${PID}_len ${FIRMWARE_SIZE}\n")
            file(APPEND "${HEADER_FILE}" "#define mt76_firmware_${PID}_is_compressed 1\n")
            file(APPEND "${HEADER_FILE}" "extern const uint8_t mt76_firmware_${PID}[mt76_firmware_${PID}_compressed_len];\n\n")
        else()
            file(APPEND "${HEADER_FILE}" "#define mt76_firmware_${PID}_len ${ACTUAL_SIZE}\n")
            file(APPEND "${HEADER_FILE}" "#define mt76_firmware_${PID}_is_compressed 0\n")
            file(APPEND "${HEADER_FILE}" "extern const uint8_t mt76_firmware_${PID}[mt76_firmware_${PID}_len];\n\n")
        endif()
        
        math(EXPR FIRMWARE_CONVERTED "${FIRMWARE_CONVERTED} + 1")
    else()
        message(STATUS "  [${PID}] Not found, using placeholder")
        file(APPEND "${OUTPUT_FILE}" "// xone_dongle_${PID}.bin (not found - placeholder)\n")
        file(APPEND "${OUTPUT_FILE}" "const uint8_t mt76_firmware_${PID}[1] = {0x00};\n\n")
        
        # Add to header - define size macro first, then use it
        file(APPEND "${HEADER_FILE}" "#define mt76_firmware_${PID}_len 1\n")
        file(APPEND "${HEADER_FILE}" "extern const uint8_t mt76_firmware_${PID}[mt76_firmware_${PID}_len];\n\n")
    endif()
endforeach()

# Close header guard
file(APPEND "${HEADER_FILE}" "#endif // FIRMWARE_DATA_H\n")

if(FIRMWARE_CONVERTED GREATER 0)
    list(LENGTH FIRMWARE_PIDS TOTAL_FIRMWARE_COUNT)
    message(STATUS "Converted ${FIRMWARE_CONVERTED}/${TOTAL_FIRMWARE_COUNT} firmware files to C arrays")
    message(STATUS "Generated: ${OUTPUT_FILE}")
    message(STATUS "Generated: ${HEADER_FILE}")
    set(FIRMWARE_DATA_AVAILABLE TRUE)
else()
    message(WARNING "No firmware files converted - using placeholders")
    message(WARNING "Adapter will not function without real firmware")
    message(STATUS "Generated: ${OUTPUT_FILE} (with placeholders)")
    message(STATUS "Generated: ${HEADER_FILE} (with placeholders)")
    set(FIRMWARE_DATA_AVAILABLE FALSE)
endif()
