name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build Project
        run: pio run -e pico
  release:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true
      - name: Build artifacts
        run: |
          rm ardwiino_script_post.py
          mv ardwiino_script_post_tool.py ardwiino_script_post.py
          cd ..
          tar cfJ firmware.tar.xz Ardwiino
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "../firmware.tar.xz"
          tag_name: latest
          target_commitish: master
